### ISSUE TITLE
[Suggestion] Add GrafX2

### ISSUE THREAD

**Issue by Code-Otto** [KenneyNL/Adobe-Alternatives#18]
With a new shiny pixel art section GrafX2 is an old player in the scene worth mentioning!
Starting development in the late 90's it is a Deluxe Paint inspired indexed color painting program heavily tailored for pixel art. Sports some neat features like Lua scripting, non-square pixel modes and emulation of display limitations from some early home computers
GPLv2 licensed, http://grafx2.chez.com/

**Comment by KenneyNL** [comment]
This has been added to the list, thank you!
