### ISSUE TITLE
[AfterEffects alternative] Apple Motion

### ISSUE THREAD

**Issue by stereoknife** [KenneyNL/Adobe-Alternatives#24]
Apple also makes a compositing/effects/motion graphics software as part of its Final Cut suite though I have never used it and I'm not sure where exactly it should be categorized so I didn't want to make a PR for it. Maybe someone who knows more about it can comment on whether it's suitable and where.

[https://www.apple.com/final-cut-pro/motion/](https://www.apple.com/final-cut-pro/motion/)

Also the website is a bit confusing as it's listed as part of Final Cut Pro and the buy button on the top right links to Final Cut Pro but it's a separate software and the "Buy Motion" link correctly points to its AppStore page.

**Comment by marieudb** [comment]
thank you!

**Comment by KenneyNL** [comment]
This has been added to the list, thank you!
