### ISSUE TITLE
iZotope RX is not free

### ISSUE THREAD

**Issue by RealJamako** [KenneyNL/Adobe-Alternatives#25]
iZotope RX has been put down as a free of charge product when it is in-fact a paid product. Cheapest tier being $64. 

Unless you are counting the free trial as a free of charge product. I apologise.

**Comment by begin-theadventure** [comment]
Yeah, maybe there should be another `Legend:` `Free trial`

**Comment by KenneyNL** [comment]
You're right, as it's only a 10-day trial I feel it isn't even worth mentioning as a 'free' product and instead might just be better suited to give the 💵 symbol.
