### ISSUE TITLE
Why not Figma? 

### ISSUE THREAD

**Issue by plcdnl** [KenneyNL/Adobe-Alternatives#44]
Why do not put figma in adobe xd alternatives?

**Comment by KenneyNL** [comment]
Because of a proposed acquisition by Adobe, please see [Wikipedia](https://en.wikipedia.org/wiki/Figma_(software))

**Comment by gingerbeardman** [comment]
Given that the acquisition didn't go ahead, I think it should be added @KenneyNL 

Cheers!
