### ISSUE TITLE
Fix: Lunacy is free⭐️ to use, subscriptions 🔒 are optional

### ISSUE THREAD

**Issue by alaa13212** [KenneyNL/Adobe-Alternatives#52]
[Icon8 Lunacy](https://icons8.com/lunacy) is actually free to use, both for personal and commercial projects.
You only pay if you want to use Icon8 graphics library or if you want cloud storage.

Details about pricing can be found here: https://lunacy.docs.icons8.com/subscriptions/

**Comment by KenneyNL** [comment]
Thanks, fixed!
