### ISSUE TITLE
Sugestion to replace armorpaint with Blender+ucupaint addon

### ISSUE THREAD

**Issue by tieguaili3d** [KenneyNL/Adobe-Alternatives#59]
I've followed development of armorpaint since the beginning and it's been abandoned for a long time, it's laggy, clumsy, incredibly limited, lacking basic features, and all-around just not a viable option if you want to actually texture anything.

Alternative that does actually work is just using Blender's texture painting kit and shader nodes enhanced by the ucupaint addon (free), which adds curvature, occlusion, light bakes, layers, and layer adjustments to give a much more complete and easy to use toolset.

**Comment by KenneyNL** [comment]
I've just checked and the latest release of ArmorPaint is Sep 25, 2023 (quite recent) and their git lists changes as recent as two days ago, so I wouldn't say it's abandoned. The provides alternatives that are available and quality is suggestive in most cases.

Currently the list doesn't include addons, Blender is already listed.

**Comment by tieguaili3d** [comment]
in all of the updates nothing has actually been improved that would make the app viable for texturing compared to the alternatives, the main issues being that if you want to alter your brush at all you have to be a node wizard since there's no built-in "follow stroke" option for your brush alpha, you don't even get the option to put in a brush alpha unless you add a few nodes (which assumes you're already familiar with building everything yourself from scratch with nodes when every other app has these features built in and teh 1 node that gives you something you don't have elsewhere is "time" (which you can easily replace with pressure for anything you actually need to do), and the shader nodes are completely different from blender, making it impossible to import blender materials even though the manual claims you can, and as far as armorpaint's procedural base textures go they're terribly limited compared to blender, al that coupled wit hthe fact that the only justifiable argument for the incredibly limited and awkward way these things are set up is "well you can just download them from other people" no one actually uses it, the only option there is armopaint cloud which has a decent number of basic materials but certainly not enough to cover all bases (not knocking cloud, it's a pretty good library and it isn't expected to be able to cover all bases, but when it's your only way to really get anything to download you're stuck if they don't have it). all that combined with the fact that you get significant jitter and loss on any stroke that's not incredibly slow and armorpaint just isn't a viable option yet, maybe it'll get there but since the issues they have are the same issues they had on release i doubt it
![brush](https://github.com/KenneyNL/Adobe-Alternatives/assets/53412281/de4cebed-21c3-468d-8945-d08e3a4bc98d)
![b-nodes](https://github.com/KenneyNL/Adobe-Alternatives/assets/53412281/4eb4f3c4-7683-41f5-90a0-5a7eff79ed0b)
![material nodes](https://github.com/KenneyNL/Adobe-Alternatives/assets/53412281/b7310b97-9f12-4875-b981-33d902b5283f)
