### ISSUE TITLE
Awesome List

### ISSUE THREAD

**Issue by LauraWebdev** [KenneyNL/Adobe-Alternatives#6]
Have you considered adjusting the repo name / adding the typical "awesome" naming that is common on Github? I think this would help discoverability of this list.

Topic: https://github.com/topics/awesome
Explaination: https://dev.to/this-is-learning/the-awesome-side-of-github-awesome-lists-2a5h

**Comment by DeveloppeurPascal** [comment]
Good idea. Just to notice : GitHub has an automatic redirection from previous URL to the new one, no links will be lost during (and after) the operation.
