### ISSUE TITLE
Suggestion: For years, this overview has been lacking Steinberg software in the list of DAWs - why?

### ISSUE THREAD

**Issue by dreikelvin** [KenneyNL/Adobe-Alternatives#69]
I request, no, I demand the addition of the following apps under DAWs:

+ Steinberg Wavelab (Mac/Win)
+ Steinberg Cubase (Mac/Win)
+ Steinberg Nuendo (Mac/Win)

Thank you!

**Comment by theMidiTamer** [comment]
+1

**Comment by KenneyNL** [comment]
Added!

**Comment by dreikelvin** [comment]
haha, that's so awesome. thanks!
