### ISSUE TITLE
Synfig is not browserbased

### ISSUE THREAD

**Issue by TheRealBlackNet** [KenneyNL/Adobe-Alternatives#81]
Synfig is not browserbased it is in the list: [Synfig](https://www.synfig.org/) (Browser)
We can see from the Page: Open-source 2D Animation Software for Windows, Linux and MacOS
Distribution it is done by gumroad, that needs a email, for 0 $ options include MacOs, Linux\Windows for 32\64 and Windows Portable 32\64.

The list should be changed 
[Synfig](https://www.synfig.org/) (Max,Win,Linux, needs eMail address)

**Comment by rodlie** [comment]
> Distribution it is done by gumroad, that needs a email, for 0 $ options include MacOs, Linux\Windows for 32\64 and Windows Portable 32\64.

Or just download it from https://github.com/synfig/synfig/releases, no registration required.

**Comment by Kazevic** [comment]
This can now be closed.
