### ISSUE TITLE
New Amazing After Effects Alternative

### ISSUE THREAD

**Issue by zcarson2** [KenneyNL/Adobe-Alternatives#94]
Please, please, please add Autograph by Left Angle to the list for After Effects alternatives! It is honestly the first TRUE alternative to AE. I've been a professional AE user for several years and Autograph is phenomenal and very promising. It is essentially exactly like how you would WANT After Effects to work and they are actively updating it and listening to feedback from it's users. If you know how to use AE, most of the main functions and workflows are the same. Plus they offer both subs AND permanent license options. I feel this is an extremely important addition for motion graphics designers, VFX artists, and compositors. As a professional that has been using AE for small and large clients, Autograph is a must for the future of these designers.

**Comment by KenneyNL** [comment]
This feels kind of like an advertisement by the creator of the software, to be honest. I'm gonna leave it closed - sorry!

**Comment by zcarson2** [comment]
Aw dang, okay. I am a legit motion graphics designer tho and I'm not from
the Left Angle company. You can see my work on my Twitter as proof if you
would like: https://x.com/PopPunkGameTime?t=orxkh4H4ubMSsnIRX8Phhg&s=09

If you still don't want to add Autograph to the list, that's fine. I just
love the software and it's legitimately what I've been wanting for years
and I'm always looking out for great alternatives. Thank you for the
consideration tho.

**Comment by LF-rvfx** [comment]
@KenneyNL This guy @zcarson2 does not have any affiliation to Left Angle.  He is just a legitimate user of Autograph.  I actually work with Left Angle as I am working for their worldwide distributor, RE:Vision Effects.  We also feel that Autograph is a great alternative, as do many other users.  Maybe you should give it some consideration. Thank you!
