### ISSUE TITLE
Visual Studio Code is open-source

### ISSUE THREAD

**Issue by lu2000luk** [KenneyNL/Adobe-Alternatives#99]
In the dreamviewer section VSCode has the wrong symbol.  It should be a ✨ Sparkle as its free and open source

**Comment by encukou** [comment]
[Visual Studio Code](https://code.visualstudio.com/) and [“Code - OSS” (the `vscode` repo)](https://github.com/microsoft/vscode) are two different things.

Visual Studio Code is, according to its home page, *built on open source*. But it [includes some parts the authors want to keep secret](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005).

You can build an editor with just the open-source parts, or download it from [someone who does](https://vscodium.com/), but you don't get that with Microsoft's shiny Download buttons, and it's not named *Visual Studio Code*.

**Comment by freeurmind** [comment]
Introducing [VSCodium](https://vscodium.com/) and [VSCodium Github](https://github.com/VSCodium/vscodium)
